# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2016 Asian Humanism Conference
title-zh: 2016 亞洲人文主義大會
email: asianhumanismcon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is open to suggestions, so contact us or if you can use github click on the pencil icon to get to the code, make your changes and when you're done click on "Propose file change".
url: "https://ash.multifarious.net" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: strangehill
github_repo: strangehill/ash/

future: true

# Build settings
markdown: kramdown

sass:
    style: compressed

exclude: [package.json, node_modules, gulpfile.js]
