# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Asian Humanism Conference
email: asianhumanismcon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is open to suggestions.
  Click on pencil icons to propose changes with a free github account.
url: "http://ash.multifarious.net" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: strangehill
# github_username: strangehill

future: true

# Build settings
markdown: kramdown

exclude: [package.json, node_modules, gulpfile.js]
